from os import getenv

JWT_SECRET_KEY = getenv("JWT_SECRET_KEY")
TOKEN_EXPIRE_MINUTES = int(getenv("TOKEN_EXPIRE_MINUTES"))
ALGORITHM = getenv("ALGORITHM")

# Para el admin
ADMIN_USERNAME = getenv("ADMIN_USERNAME")
ADMIN_PHONE = getenv("ADMIN_PHONE")
ADMIN_DOCUMENT = getenv("ADMIN_DOCUMENT")
ADMIN_ADDRESS = getenv("ADMIN_ADDRESS")
ADMIN_EMAIL = getenv("ADMIN_EMAIL")
ADMIN_PASSWORD = getenv("ADMIN_PASSWORD")


